version: '3.8'
services:
  app:
    container_name: medceu
    image: php_apache_img
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 7777:80     
    
    

  

