version: '3.8'
services:
  app:
    container_name: medceu
    image: php_apache_img
    build:
      context: ./
    volumes:
      - /Users/fernando/Desktop/repos/medceu/src:/var/www/html/
    ports:
      - 7777:80
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=minhapomba
      - MYSQL_DATABASE=medceu
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8082:3306"

